### ISSUE TITLE
[Question] React-loadable in externals

### ISSUE THREAD

**Issue by smashercosmo** [phyllisstein/react-loadable-mwe#1]
Hey @phyllisstein first of all thx for you demo. I've been playing with it for a while and what I can't understand is that why do we need to exclude react-loadable from node externals? I see, that without it it doesn't work, but really can't figure out why.

**Comment by phyllisstein** [comment]
Hey there! No problem at all---glad it came in handy. The reason for forcing Loadable into the bundle is that its code runs a check to see whether the variable `__webpack_require__` is floating around in the current scope to determine whether or not it's running under Webpack. (See [`index.js:11`](https://github.com/thejameskyle/react-loadable/blob/master/src/index.js#L11).) As an extern, outside of the bundle's scope, it'd be unable to see that variable and consequently wouldn't bother gathering and caching the module IDs you need to preload your chunks. (Q.v. [`index.js:136`](https://github.com/thejameskyle/react-loadable/blob/master/src/index.js#L136).)

**Comment by smashercosmo** [comment]
Yes, now it looks obvious) Thank you for the explanation.
